name: Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Run SSH Script
      run: |
        ./votre_script.sh
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD_ONE_BUILD_PLUS }}
