name: Deploy Laravel Project on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v4
      - name: SSH and run 'composer install' on the remote server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD_ONE_BUILD_PLUS }}" ssh -o StrictHostKeyChecking=no -p 65002 u212330119@89.117.9.183 'cd ./obp/OBP/ && composer2 install'
