name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PASSWORD_ONE_BUILD_PLUS }}

    - name: Deploy to Server
      run: |
        ssh -p 65002 ${{ secrets.SSH_USERNAME_ONE_BUILD_PLUS }}@${{ secrets.SSH_HOST_ONE_BUILD_PLUS }} "cd /path/to/your/laravel/project && git pull origin main && php artisan optimize"