name: Deploy Laravel Project on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v4
      - name: SSH and run 'composer install' on the remote server
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD_ONE_BUILD_PLUS }} ssh -o StrictHostKeyChecking=no -p 65002 ${{ secrets.SSH_USERNAME_ONE_BUILD_PLUS }}@${{ secrets.SSH_HOST_ONE_BUILD_PLUS }} 'cd ./obp/OBP/ && composer install'
